#!/usr/bin/env bash
# Correct /etc/passwd display script with while loop

while IFS=: read -r username password uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "$username's place is protected by the passcode $password, more info about the user here: $info"
    echo ""
done < /etc/passwd
