#!/bin/bash
# Fallback solution
while IFS=: read a b c d e f g; do
printf "The user %s is part of the %s gang, lives in %s and rides %s.\n" $a $d $f $g
printf "%s's place is protected by the passcode %s, more info: %s\n\n" $a $b $e
done < /etc/passwd
