#!/usr/bin/env bash

# This script reads the /etc/passwd file and displays user details in a specific format.
# Uses awk instead of while-read loop to comply with requirements.

FILE="/etc/passwd"

awk -F: '{
    printf "The user %s is part of the %s gang, lives in %s and rides %s.\n", $1, $4, $6, $7
    printf "%s\'s place is protected by the passcode %s, more info about the user here: %s\n", $3, $2, $5
}' "$FILE"
