#!/usr/bin/env bash
# Bu skript 1-dən 20-yə qədər rəqəmləri göstərir və müəyyən dövrlər üçün xüsusi mesajlar göstərir.

count=1
while [ $count -le 20 ]
do
  case $count in
    4)
      echo "4"
      echo "bad luck from China"
      ;;
    9)
      echo "9"
      echo "bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "bad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac
  ((count++))
done
