#!/usr/bin/env bash
# This script stops '4-to_infinity_and_beyond' process without using kill or killall

pgrep -u "$USER" -f 4-to_infinity_and_beyond | while read -r pid; do
  : > "/proc/$pid/fd/0" 2>/dev/null
done
