#!/usr/bin/env bash
# Script to kill the 7-highlander process

# Find the PID of 7-highlander
pid=$(pgrep -f "7-highlander")

# If process exists, kill it
if [ -n "$pid" ]; then
    kill -9 "$pid"
fi
